name: Complex workflow

on: 
    push:
        branches: ["partie-2/chapitre-2/section-4-fin"]
    

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v3
              with: 
                node-version: 18
                cache: 'npm'

            - name: Install libraries and dependencies
              run: npm install
              
            - name: Run linter
              run: npm run lint

            - name: Run typecheck
              run: npm run typecheck

    build_and_test:
        needs: lint
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Node
            uses: actions/setup-node@v3
            with: 
              node-version: 18
              cache: 'npm'

          - name: Run project build
            run: npm run build
            
          - name: Run tests
            run: npm run test

          - name: Print Congratulations message
            run: "Congrats ! Workflow passed successfully"
          
                  
