name: Run Checks Workflow

on: push

jobs:
    run-checks:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.1
              with:
                node-version: 18

            - name: Verify Node Version
              run: node -v

            - name: Install project libs and dependencies
              run: npm i

            - name: Run Linter 
              run: npm run lint
            
            - name: Run Typescript Typechecker
              run: npm run typecheck

            - name: Success message when Job done
              run: echo "Job done!"