name: Run Checks Workflow

on: push

jobs:
    run-checks:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # - name: Setup Node.js environment
            #   uses: actions/setup-node@v4.0.1
            #   with:
            #     node-version: 18

            - name: install Node v18
              run: npm install node@18

            - name: Verify Node Version
              run: node -v